name: Deploy Master Branch

on:
  push:
    branches:
      - master
      - new-deployment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Bundler
      run: sudo gem install bundler
    - name: Cache bundle
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install Jekyll
      run: bundle install
    - name: Build the site with Jekyll
      run: |
        bundle exec jekyll build --future
    - name: Upload
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "delta.chat"
        port: 22
        local: "_site"
        remote: "/var/www/html/"

